# Generated by Django 2.1.7 on 2019-12-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('lifetime', models.DateTimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WxToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('lifetime', models.DateTimeField(default=0)),
            ],
        ),
    ]
