# Generated by Django 2.2.2 on 2019-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30, verbose_name='纬度')),
                ('longitude', models.CharField(max_length=30, verbose_name='经度')),
                ('date', models.CharField(max_length=30, verbose_name='日期')),
                ('time', models.CharField(max_length=30, verbose_name='时间')),
            ],
            options={
                'verbose_name': '星座信息',
                'verbose_name_plural': '星座信息',
            },
        ),
    ]
