# Generated by Django 2.1.7 on 2019-10-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrologychart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AscSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_asc', models.CharField(max_length=30, verbose_name='上升星座')),
                ('meaning', models.TextField(verbose_name='上升星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='CHIRONSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_chiron', models.CharField(max_length=30, verbose_name='凯龙星星座')),
                ('meaning', models.TextField(verbose_name='凯龙星星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='DesSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_des', models.CharField(max_length=30, verbose_name='下降星座')),
                ('meaning', models.TextField(verbose_name='下降星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='ICSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_ic', models.CharField(max_length=30, verbose_name='天底星座')),
                ('meaning', models.TextField(verbose_name='天底星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='JUPITERSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_jupiter', models.CharField(max_length=30, verbose_name='木星星座')),
                ('meaning', models.TextField(verbose_name='木星星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='MARSSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_mars', models.CharField(max_length=30, verbose_name='火星星座')),
                ('meaning', models.TextField(verbose_name='火星星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='MCSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_mc', models.CharField(max_length=30, verbose_name='天顶星座')),
                ('meaning', models.TextField(verbose_name='天顶星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='MERCURYSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_mercury', models.CharField(max_length=30, verbose_name='水星星座')),
                ('meaning', models.TextField(verbose_name='水星星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='MOONSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_moon', models.CharField(max_length=30, verbose_name='月亮星座')),
                ('meaning', models.TextField(verbose_name='月亮星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='NEPTUNESign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_neptune', models.CharField(max_length=30, verbose_name='海王星星座')),
                ('meaning', models.TextField(verbose_name='海王星星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='NNodeSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_nnode', models.CharField(max_length=30, verbose_name='北交点星座')),
                ('meaning', models.TextField(verbose_name='北交点星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='PLUTOSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_pluto', models.CharField(max_length=30, verbose_name='冥王星星座')),
                ('meaning', models.TextField(verbose_name='冥王星星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='SATURNSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_saturn', models.CharField(max_length=30, verbose_name='土星星座')),
                ('meaning', models.TextField(verbose_name='土星星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='SNodeSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_snode', models.CharField(max_length=30, verbose_name='南交点星座')),
                ('meaning', models.TextField(verbose_name='南交点星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='SunSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_sun', models.CharField(max_length=30, verbose_name='太阳星座')),
                ('meaning', models.TextField(verbose_name='太阳星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='URANUSSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_uranus', models.CharField(max_length=30, verbose_name='天王星星座')),
                ('meaning', models.TextField(verbose_name='天王星星座解读')),
            ],
        ),
        migrations.CreateModel(
            name='VENUSSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_venus', models.CharField(max_length=30, verbose_name='金星星座')),
                ('meaning', models.TextField(verbose_name='金星星座解读')),
            ],
        ),
        migrations.AddField(
            model_name='astrologyinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astrology', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
