# Generated by Django 2.1.7 on 2019-10-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologychart', '0002_auto_20191016_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOUSE1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第一宫星座')),
                ('definition', models.TextField(default='', verbose_name='第一宫定义')),
                ('meaning', models.TextField(verbose_name='第一宫星座解读')),
            ],
            options={
                'verbose_name': '第一宫星座',
                'verbose_name_plural': '第一宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第十宫星座')),
                ('definition', models.TextField(default='', verbose_name='第十宫定义')),
                ('meaning', models.TextField(verbose_name='第十宫星座解读')),
            ],
            options={
                'verbose_name': '第十宫星座',
                'verbose_name_plural': '第十宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第十一宫星座')),
                ('definition', models.TextField(default='', verbose_name='第十一宫定义')),
                ('meaning', models.TextField(verbose_name='第十一宫星座解读')),
            ],
            options={
                'verbose_name': '第十一宫星座',
                'verbose_name_plural': '第十一宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第十二宫星座')),
                ('definition', models.TextField(default='', verbose_name='第十二宫定义')),
                ('meaning', models.TextField(verbose_name='第十二宫星座解读')),
            ],
            options={
                'verbose_name': '第十二宫星座',
                'verbose_name_plural': '第十二宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第二宫星座')),
                ('definition', models.TextField(default='', verbose_name='第二宫定义')),
                ('meaning', models.TextField(verbose_name='第二宫星座解读')),
            ],
            options={
                'verbose_name': '第二宫星座',
                'verbose_name_plural': '第二宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第三宫星座')),
                ('definition', models.TextField(default='', verbose_name='第三宫定义')),
                ('meaning', models.TextField(verbose_name='第三宫星座解读')),
            ],
            options={
                'verbose_name': '第三宫星座',
                'verbose_name_plural': '第三宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第四宫宫座')),
                ('definition', models.TextField(default='', verbose_name='第四宫定义')),
                ('meaning', models.TextField(verbose_name='第四宫星座解读')),
            ],
            options={
                'verbose_name': '第四宫星座',
                'verbose_name_plural': '第四宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第五宫星座')),
                ('definition', models.TextField(default='', verbose_name='第五宫定义')),
                ('meaning', models.TextField(verbose_name='第五宫星座解读')),
            ],
            options={
                'verbose_name': '第五宫星座',
                'verbose_name_plural': '第五宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第六宫星座')),
                ('definition', models.TextField(default='', verbose_name='第六宫定义')),
                ('meaning', models.TextField(verbose_name='第六宫星座解读')),
            ],
            options={
                'verbose_name': '第六宫星座',
                'verbose_name_plural': '第六宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第七宫星座')),
                ('definition', models.TextField(default='', verbose_name='第七宫定义')),
                ('meaning', models.TextField(verbose_name='第七宫星座解读')),
            ],
            options={
                'verbose_name': '第七宫星座',
                'verbose_name_plural': '第七宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第八宫星座')),
                ('definition', models.TextField(default='', verbose_name='第八宫定义')),
                ('meaning', models.TextField(verbose_name='第八宫星座解读')),
            ],
            options={
                'verbose_name': '第八宫星座',
                'verbose_name_plural': '第八宫星座',
            },
        ),
        migrations.CreateModel(
            name='HOUSE9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30, verbose_name='第九宫星座')),
                ('definition', models.TextField(default='', verbose_name='第九宫定义')),
                ('meaning', models.TextField(verbose_name='第九宫星座解读')),
            ],
            options={
                'verbose_name': '第九宫星座',
                'verbose_name_plural': '第九宫星座',
            },
        ),
        migrations.AlterModelOptions(
            name='ascsign',
            options={'verbose_name': '上升星座', 'verbose_name_plural': '上升星座'},
        ),
        migrations.AlterModelOptions(
            name='chironsign',
            options={'verbose_name': '凯龙星星座', 'verbose_name_plural': '凯龙星星座'},
        ),
        migrations.AlterModelOptions(
            name='dessign',
            options={'verbose_name': '下降星座', 'verbose_name_plural': '下降星座'},
        ),
        migrations.AlterModelOptions(
            name='icsign',
            options={'verbose_name': '天底星座', 'verbose_name_plural': '天底星座'},
        ),
        migrations.AlterModelOptions(
            name='jupitersign',
            options={'verbose_name': '木星星座', 'verbose_name_plural': '木星星座'},
        ),
        migrations.AlterModelOptions(
            name='marssign',
            options={'verbose_name': '火星星座', 'verbose_name_plural': '火星星座'},
        ),
        migrations.AlterModelOptions(
            name='mcsign',
            options={'verbose_name': '天顶星座', 'verbose_name_plural': '天顶星座'},
        ),
        migrations.AlterModelOptions(
            name='mercurysign',
            options={'verbose_name': '水星星座', 'verbose_name_plural': '水星星座'},
        ),
        migrations.AlterModelOptions(
            name='moonsign',
            options={'verbose_name': '月亮星座', 'verbose_name_plural': '月亮星座'},
        ),
        migrations.AlterModelOptions(
            name='neptunesign',
            options={'verbose_name': '海王星星座', 'verbose_name_plural': '海王星星座'},
        ),
        migrations.AlterModelOptions(
            name='nnodesign',
            options={'verbose_name': '北交点星座', 'verbose_name_plural': '北交点星座'},
        ),
        migrations.AlterModelOptions(
            name='plutosign',
            options={'verbose_name': '冥王星星座', 'verbose_name_plural': '冥王星星座'},
        ),
        migrations.AlterModelOptions(
            name='saturnsign',
            options={'verbose_name': '土星星座', 'verbose_name_plural': '土星星座'},
        ),
        migrations.AlterModelOptions(
            name='snodesign',
            options={'verbose_name': '南交点星座', 'verbose_name_plural': '南交点星座'},
        ),
        migrations.AlterModelOptions(
            name='sunsign',
            options={'verbose_name': '太阳星座', 'verbose_name_plural': '太阳星座'},
        ),
        migrations.AlterModelOptions(
            name='uranussign',
            options={'verbose_name': '天王星星座', 'verbose_name_plural': '天王星星座'},
        ),
        migrations.AlterModelOptions(
            name='venussign',
            options={'verbose_name': '金星星座', 'verbose_name_plural': '金星星座'},
        ),
        migrations.AddField(
            model_name='ascsign',
            name='definition',
            field=models.TextField(default='', verbose_name='上升星座定义'),
        ),
        migrations.AddField(
            model_name='astrologyinfo',
            name='accuracy',
            field=models.CharField(max_length=30, null=True, verbose_name='准确度反馈'),
        ),
        migrations.AddField(
            model_name='astrologyinfo',
            name='feedback',
            field=models.TextField(null=True, verbose_name='意见反馈'),
        ),
        migrations.AddField(
            model_name='chironsign',
            name='definition',
            field=models.TextField(default='', verbose_name='凯龙星星座定义'),
        ),
        migrations.AddField(
            model_name='dessign',
            name='definition',
            field=models.TextField(default='', verbose_name='下降星座定义'),
        ),
        migrations.AddField(
            model_name='icsign',
            name='definition',
            field=models.TextField(default='', verbose_name='天底星座定义'),
        ),
        migrations.AddField(
            model_name='jupitersign',
            name='definition',
            field=models.TextField(default='', verbose_name='木星星座定义'),
        ),
        migrations.AddField(
            model_name='marssign',
            name='definition',
            field=models.TextField(default='', verbose_name='火星星座定义'),
        ),
        migrations.AddField(
            model_name='mcsign',
            name='definition',
            field=models.TextField(default='', verbose_name='天顶星座定义'),
        ),
        migrations.AddField(
            model_name='mercurysign',
            name='definition',
            field=models.TextField(default='', verbose_name='水星星座定义'),
        ),
        migrations.AddField(
            model_name='moonsign',
            name='definition',
            field=models.TextField(default='', verbose_name='月亮星座定义'),
        ),
        migrations.AddField(
            model_name='neptunesign',
            name='definition',
            field=models.TextField(default='', verbose_name='海王星星座定义'),
        ),
        migrations.AddField(
            model_name='nnodesign',
            name='definition',
            field=models.TextField(default='', verbose_name='北交点星座定义'),
        ),
        migrations.AddField(
            model_name='plutosign',
            name='definition',
            field=models.TextField(default='', verbose_name='冥王星星座定义'),
        ),
        migrations.AddField(
            model_name='saturnsign',
            name='definition',
            field=models.TextField(default='', verbose_name='土星星座定义'),
        ),
        migrations.AddField(
            model_name='snodesign',
            name='definition',
            field=models.TextField(default='', verbose_name='南交点星座定义'),
        ),
        migrations.AddField(
            model_name='sunsign',
            name='definition',
            field=models.TextField(default='', verbose_name='太阳星座定义'),
        ),
        migrations.AddField(
            model_name='uranussign',
            name='definition',
            field=models.TextField(default='', verbose_name='天王星星座定义'),
        ),
        migrations.AddField(
            model_name='venussign',
            name='definition',
            field=models.TextField(default='', verbose_name='金星星座定义'),
        ),
    ]
