# Generated by Django 2.1.7 on 2019-10-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologychart', '0003_auto_20191020_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='chironsign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='jupitersign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='marssign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='mercurysign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='moonsign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='neptunesign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='plutosign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='saturnsign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='sunsign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='uranussign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
        migrations.AddField(
            model_name='venussign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='太阳宫位解读'),
        ),
    ]
