# Generated by Django 2.1.7 on 2019-10-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologychart', '0004_auto_20191020_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jupitersign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='木星宫位解读'),
        ),
        migrations.AlterField(
            model_name='marssign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='火星宫位解读'),
        ),
        migrations.AlterField(
            model_name='mercurysign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='水星宫位解读'),
        ),
        migrations.AlterField(
            model_name='moonsign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='月亮宫位解读'),
        ),
        migrations.AlterField(
            model_name='neptunesign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='海王星宫位解读'),
        ),
        migrations.AlterField(
            model_name='plutosign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='冥王星宫位解读'),
        ),
        migrations.AlterField(
            model_name='saturnsign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='土星宫位解读'),
        ),
        migrations.AlterField(
            model_name='uranussign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='天王星宫位解读'),
        ),
        migrations.AlterField(
            model_name='venussign',
            name='house_meaning',
            field=models.TextField(default='', verbose_name='金星宫位解读'),
        ),
    ]
