# Generated by Django 2.1.7 on 2019-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologychart', '0005_auto_20191020_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstellationIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constellation', models.CharField(max_length=30, verbose_name='星座')),
                ('introduction', models.TextField(verbose_name='介绍')),
            ],
            options={
                'verbose_name': '星座介绍',
                'verbose_name_plural': '星座介绍',
            },
        ),
        migrations.CreateModel(
            name='HouseIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=30, verbose_name='宫位')),
                ('introduction', models.TextField(verbose_name='介绍')),
            ],
            options={
                'verbose_name': '宫位介绍',
                'verbose_name_plural': '宫位介绍',
            },
        ),
        migrations.CreateModel(
            name='PlanetIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(max_length=30, verbose_name='行星')),
                ('introduction', models.TextField(verbose_name='介绍')),
            ],
            options={
                'verbose_name': '行星介绍',
                'verbose_name_plural': '行星介绍',
            },
        ),
        migrations.AlterModelOptions(
            name='astrologyinfo',
            options={'verbose_name': '个人星座信息', 'verbose_name_plural': '个人星座信息'},
        ),
        migrations.RemoveField(
            model_name='ascsign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='chironsign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='dessign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house1',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house10',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house11',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house12',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house2',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house3',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house4',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house5',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house6',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house7',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house8',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='house9',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='icsign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='jupitersign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='marssign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='mcsign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='mercurysign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='moonsign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='neptunesign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='nnodesign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='plutosign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='saturnsign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='snodesign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='sunsign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='uranussign',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='venussign',
            name='definition',
        ),
    ]
