# Generated by Django 2.2.2 on 2019-08-22 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ('-timestamp',), 'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='接收'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='发送'),
        ),
    ]
