# Generated by Django 2.1.7 on 2020-05-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleprocessflow',
            name='approvaldate',
        ),
        migrations.RemoveField(
            model_name='articleprocessflow',
            name='description',
        ),
        migrations.RemoveField(
            model_name='articleprocessflow',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='articleprocessflow',
            name='modifytime',
        ),
        migrations.RemoveField(
            model_name='articleprocessflow',
            name='opinion',
        ),
        migrations.RemoveField(
            model_name='articleprocessflow',
            name='state',
        ),
        migrations.RemoveField(
            model_name='processstaterecord',
            name='time',
        ),
        migrations.AddField(
            model_name='processstaterecord',
            name='approvaldate',
            field=models.DateTimeField(auto_now=True, verbose_name='处理时间'),
        ),
        migrations.AddField(
            model_name='processstaterecord',
            name='description',
            field=models.TextField(default='', verbose_name='发起描述'),
        ),
        migrations.AddField(
            model_name='processstaterecord',
            name='modifytime',
            field=models.DateTimeField(auto_now=True, verbose_name='发起时间'),
        ),
        migrations.AddField(
            model_name='processstaterecord',
            name='opinion',
            field=models.TextField(default='', verbose_name='处理意见'),
        ),
    ]
