# Generated by Django 2.1.7 on 2020-05-02 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20200502_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleprocessflow',
            old_name='applicationdate',
            new_name='application_time',
        ),
        migrations.RenameField(
            model_name='articleprocessflow',
            old_name='approver',
            new_name='approvers',
        ),
        migrations.RenameField(
            model_name='processstaterecord',
            old_name='handle',
            new_name='this_step_handle',
        ),
        migrations.RenameField(
            model_name='processstaterecord',
            old_name='opinion',
            new_name='this_step_opinion',
        ),
        migrations.RenameField(
            model_name='processstaterecord',
            old_name='state',
            new_name='this_step_state',
        ),
        migrations.RenameField(
            model_name='processstaterecord',
            old_name='approvaldate',
            new_name='this_step_time',
        ),
        migrations.RemoveField(
            model_name='processstaterecord',
            name='approve_user',
        ),
        migrations.RemoveField(
            model_name='processstaterecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='processstaterecord',
            name='handle_user',
        ),
        migrations.RemoveField(
            model_name='processstaterecord',
            name='modifytime',
        ),
        migrations.AddField(
            model_name='processstaterecord',
            name='next_step_user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_step_user', to=settings.AUTH_USER_MODEL, verbose_name='当前处理人'),
        ),
        migrations.AddField(
            model_name='processstaterecord',
            name='this_step_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_step_user', to=settings.AUTH_USER_MODEL, verbose_name='当前发起人'),
        ),
    ]
