# Generated by Django 2.1.7 on 2020-05-02 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20200502_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstaterecord',
            name='next_step_user',
        ),
        migrations.AddField(
            model_name='processstaterecord',
            name='next_step_user',
            field=models.ManyToManyField(default='', related_name='next_step_user', to=settings.AUTH_USER_MODEL, verbose_name='下一步处理人'),
        ),
        migrations.AlterField(
            model_name='processstaterecord',
            name='this_step_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_step_user', to=settings.AUTH_USER_MODEL, verbose_name='当前处理人'),
        ),
    ]
