# Generated by Django 2.1.7 on 2020-05-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200502_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='state',
            field=models.CharField(default='草稿', max_length=200, verbose_name='当前状态'),
        ),
    ]
