# Generated by Django 2.2.2 on 2019-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('host', models.CharField(max_length=40)),
                ('usage_system', models.FloatField(null=True)),
                ('usage_user', models.FloatField(null=True)),
                ('usage_softirq', models.FloatField(null=True)),
                ('usage_iowait', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('host', models.CharField(max_length=40)),
                ('used_percent', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcstatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('host', models.CharField(max_length=100)),
                ('exe', models.CharField(max_length=40)),
                ('pid', models.FloatField()),
                ('cpu_usage', models.FloatField(null=True)),
                ('memory_rss', models.FloatField(null=True)),
            ],
        ),
    ]
